export const dummyData = {
  consignee: {
    name: "TEST NAME",
    address:
      "NO. 5-2, JALAN PUTRA MAHKOTA 7/88, SEKSYEN 7, PUTRA HEIGHTS, 47550 SUBANG JAYA, SELANGOR DARUL EHSAN, MALAYSIA",
    accountNumber: "100029",
    id: "",
  },
  shipper: {
    name: "TEST NAME",
    address:
      "NO. 5-2, JALAN PUTRA MAHKOTA 7/88, SEKSYEN 7, PUTRA HEIGHTS, 47550 SUBANG JAYA, SELANGOR DARUL EHSAN, MALAYSIA",
    accountNumber: "100223",
    id: "",
  },
  agentNameAndCity: "99Speed LGK LGK",
  tableItems: [
    {
      noOfPieces: "16",
      grossWeight: "600",
      unit: "K",
      rateClass: "Q",
      commodityItemNo: "0001",
      chargeableWeight: "600",
      rate: "5",
      total: "3000",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "10",
      grossWeight: "450",
      unit: "K",
      rateClass: "R",
      commodityItemNo: "0002",
      chargeableWeight: "450",
      rate: "4.5",
      total: "2025",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "20",
      grossWeight: "800",
      unit: "K",
      rateClass: "S",
      commodityItemNo: "0003",
      chargeableWeight: "800",
      rate: "6",
      total: "4800",
      natureAndQuantity: "Medium.. nature and quantity text",
    },
    {
      noOfPieces: "12",
      grossWeight: "500",
      unit: "K",
      rateClass: "T",
      commodityItemNo: "0004",
      chargeableWeight: "500",
      rate: "5.2",
      total: "2600",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "18",
      grossWeight: "720",
      unit: "K",
      rateClass: "U",
      commodityItemNo: "0005",
      chargeableWeight: "720",
      rate: "5.8",
      total: "4176",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "25",
      grossWeight: "1000",
      unit: "K",
      rateClass: "V",
      commodityItemNo: "0006",
      chargeableWeight: "1000",
      rate: "7",
      total: "7000",
      natureAndQuantity: "Large.. nature and quantity text",
    },
    {
      noOfPieces: "16",
      grossWeight: "600",
      unit: "K",
      rateClass: "Q",
      commodityItemNo: "0001",
      chargeableWeight: "600",
      rate: "5",
      total: "3000",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "10",
      grossWeight: "450",
      unit: "K",
      rateClass: "R",
      commodityItemNo: "0002",
      chargeableWeight: "450",
      rate: "4.5",
      total: "2025",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "20",
      grossWeight: "800",
      unit: "K",
      rateClass: "S",
      commodityItemNo: "0003",
      chargeableWeight: "800",
      rate: "6",
      total: "4800",
      natureAndQuantity: "Medium.. nature and quantity text",
    },
    {
      noOfPieces: "12",
      grossWeight: "500",
      unit: "K",
      rateClass: "T",
      commodityItemNo: "0004",
      chargeableWeight: "500",
      rate: "5.2",
      total: "2600",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "18",
      grossWeight: "720",
      unit: "K",
      rateClass: "U",
      commodityItemNo: "0005",
      chargeableWeight: "720",
      rate: "5.8",
      total: "4176",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "25",
      grossWeight: "1000",
      unit: "K",
      rateClass: "V",
      commodityItemNo: "0006",
      chargeableWeight: "1000",
      rate: "7",
      total: "7000",
      natureAndQuantity: "Large.. nature and quantity text",
    },
    {
      noOfPieces: "16",
      grossWeight: "600",
      unit: "K",
      rateClass: "Q",
      commodityItemNo: "0001",
      chargeableWeight: "600",
      rate: "5",
      total: "3000",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "10",
      grossWeight: "450",
      unit: "K",
      rateClass: "R",
      commodityItemNo: "0002",
      chargeableWeight: "450",
      rate: "4.5",
      total: "2025",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "20",
      grossWeight: "800",
      unit: "K",
      rateClass: "S",
      commodityItemNo: "0003",
      chargeableWeight: "800",
      rate: "6",
      total: "4800",
      natureAndQuantity: "Medium.. nature and quantity text",
    },
    {
      noOfPieces: "12",
      grossWeight: "500",
      unit: "K",
      rateClass: "T",
      commodityItemNo: "0004",
      chargeableWeight: "500",
      rate: "5.2",
      total: "2600",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "18",
      grossWeight: "720",
      unit: "K",
      rateClass: "U",
      commodityItemNo: "0005",
      chargeableWeight: "720",
      rate: "5.8",
      total: "4176",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "25",
      grossWeight: "1000",
      unit: "K",
      rateClass: "V",
      commodityItemNo: "0006",
      chargeableWeight: "1000",
      rate: "7",
      total: "7000",
      natureAndQuantity: "Large.. nature and quantity text",
    },
    {
      noOfPieces: "16",
      grossWeight: "600",
      unit: "K",
      rateClass: "Q",
      commodityItemNo: "0001",
      chargeableWeight: "600",
      rate: "5",
      total: "3000",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "10",
      grossWeight: "450",
      unit: "K",
      rateClass: "R",
      commodityItemNo: "0002",
      chargeableWeight: "450",
      rate: "4.5",
      total: "2025",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "20",
      grossWeight: "800",
      unit: "K",
      rateClass: "S",
      commodityItemNo: "0003",
      chargeableWeight: "800",
      rate: "6",
      total: "4800",
      natureAndQuantity: "Medium.. nature and quantity text",
    },
    {
      noOfPieces: "12",
      grossWeight: "500",
      unit: "K",
      rateClass: "T",
      commodityItemNo: "0004",
      chargeableWeight: "500",
      rate: "5.2",
      total: "2600",
      natureAndQuantity: "Long.. nature and quantity text",
    },
    {
      noOfPieces: "18",
      grossWeight: "720",
      unit: "K",
      rateClass: "U",
      commodityItemNo: "0005",
      chargeableWeight: "720",
      rate: "5.8",
      total: "4176",
      natureAndQuantity: "Short.. nature and quantity text",
    },
    {
      noOfPieces: "25",
      grossWeight: "1000",
      unit: "K",
      rateClass: "V",
      commodityItemNo: "0006",
      chargeableWeight: "1000",
      rate: "7",
      total: "7000",
      natureAndQuantity: "Large.. nature and quantity text",
    },
  ],
};
